"""Inject today's ISO date into config.extra.build_date at build time.

Used by overrides/main.html as a fallback for JSON-LD datePublished/dateModified
when a page does not declare its own `date:` frontmatter. Generating dynamically
avoids checking a hardcoded date into git (which would otherwise make every page
look "updated on 2026-04-14" forever).
"""

from datetime import date
from pathlib import Path
import json
import re


RAW_ANGLE_TOKEN_RE = re.compile(
    r"<(?=(?:\d|[.;=]|/?>(?!\w)|/[A-Z][A-Z0-9_-]*>|[A-Z][A-Z0-9_-]*>))"
)


def _patch_mkdocs_raw_html_scanner():
    """Allow Markdown text tokens like `<;>` without rewriting source notes."""
    try:
        import mkdocs.structure.pages as pages
    except Exception:  # pragma: no cover
        return

    preprocessor = getattr(pages, "_RawHTMLPreprocessor", None)
    handler = getattr(pages, "_HTMLHandler", None)
    if preprocessor is None or handler is None:
        return
    if getattr(preprocessor, "_paper_notes_angle_patch", False):
        return

    def run(self, lines):
        parser = handler()
        scanner_text = RAW_ANGLE_TOKEN_RE.sub("&lt;", "\n".join(lines))
        parser.feed(scanner_text)
        parser.close()
        self.present_anchor_ids = parser.present_anchor_ids
        return lines

    preprocessor.run = run
    preprocessor._paper_notes_angle_patch = True


def on_config(config, **kwargs):
    _patch_mkdocs_raw_html_scanner()

    extra = config.setdefault("extra", {})
    extra["build_date"] = date.today().isoformat()

    # Load bilingual URL intersection generated by parent script.
    # Templates emit hreflang only for these URLs to avoid en-side 404s.
    cfg_path = Path(config["config_file_path"]).resolve().parent
    pairs_file = cfg_path / ".hreflang_pairs.json"
    pairs: set[str] = set()
    if pairs_file.exists():
        try:
            pairs = set(json.loads(pairs_file.read_text(encoding="utf-8")))
        except Exception as e:  # pragma: no cover
            print(f"[hreflang] Warning: failed to load {pairs_file}: {e}")
    else:
        print(f"[hreflang] Note: {pairs_file} not found — hreflang tags disabled")
    extra["hreflang_pairs"] = pairs

    return config
